version: '2.2'
services:
  app:
    image: microservice
    ports:
    - "9090:8080"
    depends_on:
    - db
  db:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres
